export const DOCTORS = [
  {
    id: 1,
    name: 'Dr. Sara Al-Mutairi',
    specialty: 'Fertility doctor',
    experience: '10+ Years Experience',
    bio: 'Dr. Sara Al-Mutairi is a fertility specialist with 10 years of experience helping couples achieve their family goals. She combines medical expertise with compassionate care.',
    avatar: 'https://images.unsplash.com/photo-1594824476967-48c8b964273f?auto=format&fit=crop&q=80&w=400',
  },
  {
    id: 2,
    name: 'Dr. Mariam Al-Saadi',
    specialty: 'Reproductive Medicine',
    experience: '8+ Years Experience',
    bio: 'Dr. Mariam Al-Saadi specializes in reproductive health and hormone therapy for couples.',
    avatar: 'https://images.unsplash.com/photo-1651008376811-b90baee60c1f?auto=format&fit=crop&q=80&w=400',
  },
  {
    id: 3,
    name: 'Dr. Hassan',
    specialty: 'Physiotherapist',
    experience: '12+ Years Experience',
    bio: 'Experienced physiotherapist focused on improving mobility, relieving pain, and helping patients regain strength and independence.',
    avatar: 'https://images.unsplash.com/photo-1622253692010-333f2da6031d?auto=format&fit=crop&q=80&w=400',
  },
  {
    id: 4,
    name: 'Dr. Khalid',
    specialty: 'Fertility doctor',
    experience: '6+ Years Experience',
    bio: 'Dr. Khalid helps couples navigate fertility treatment with personalized care plans.',
    avatar: 'https://images.unsplash.com/photo-1666887360742-974c8fce8e6b?auto=format&fit=crop&q=80&w=400',
  },
  {
    id: 5,
    name: 'Dr. Amjad Noor',
    specialty: 'Reproductive Medicine',
    experience: '9+ Years Experience',
    bio: 'Dr. Fatima Noor is dedicated to hormone therapy and reproductive wellness.',
    avatar: 'https://images.unsplash.com/photo-1550831107-1553da8c8464?auto=format&fit=crop&q=80&w=400',
  },
  {
    id: 6,
    name: 'Dr. Amad Raza',
    specialty: 'Neurosurgeon',
    experience: '7+ Years Experience',
    bio: 'Experienced neurosurgeon specializing in the diagnosis and treatment of brain, spine, and nervous system conditions.',
    avatar: 'https://images.unsplash.com/photo-1584467735815-f778f274e296?auto=format&fit=crop&q=80&w=400',
  },
];