// Sirf service ka static content (title/description/price/icon).
// Doctor ab yahan hardcode nahi — real doctors list se index ke hisaab se assign hota hai
export const SERVICES = [
    {
        id: 1,
        slug: 'stronger-erections',
        title: 'Have stronger erections.',
        category: 'Sexual Wellbeing',
        price: 150,
        featured: true,
        description: 'Lorem ipsum dolor sit amet, consectetur adipiscing elit. Sed non purus at lorem tincidunt tincidunt.',
        included: 'Test Service',
        icon: '💊',
    },
    {
        id: 2,
        slug: 'balance-hormones',
        title: 'Balance your hormones',
        category: 'Sexual Wellbeing',
        price: 300,
        featured: false,
        description: 'Restore hormonal balance with expert guidance and personalized treatment plans.',
        included: 'Hormone Panel Test',
    },
    {
        id: 3,
        slug: 'safe-birth-control',
        title: 'Safe birth control',
        category: 'Fertility',
        price: 120,
        featured: false,
        description: 'Expert consultation on safe and effective contraceptive options.',
        included: 'Consultation + Follow-up',
    },
    {
        id: 4,
        slug: 'tackle-anxiety',
        title: 'Tackle anxiety or stress',
        category: 'Mental Wellness',
        price: 140,
        featured: false,
        description: 'Talk to a specialist about anxiety and stress management strategies.',
        included: 'Talk Therapy Session',
    },
    {
        id: 5,
        slug: 'pain-free-intimacy',
        title: 'Pain-free intimacy',
        category: 'Sexual Wellbeing',
        price: 160,
        featured: false,
        description: 'Consultation for pain-free intimate wellness and related concerns.',
        included: 'Consultation + Treatment Plan',
    },
    {
        id: 6,
        slug: 'stress-relaxation',
        title: 'Stress Relaxation',
        category: 'Mental Wellness',
        price: 130,
        featured: false,
        description: 'Guided sessions designed to help you relax and manage daily stress.',
        included: 'Guided Session',
    },
    {
        id: 7,
        slug: 'testing-service',
        title: 'Testing Service',
        category: 'Lab Test',
        price: 90,
        featured: false,
        description: 'Book a comprehensive lab testing service with fast results.',
        included: 'Lab Test Kit',
    },
];